version: '3.3'

services:
  web:
    image: lakshanbanneheke/stockpilot:latest
    container_name: backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_RUN_PORT=80
      - SECRET_KEY="stockpilot"
      - MONGO_URL_GENERAL=mongodb+srv://SEPU02:general123@sepcluster.yjn4m.mongodb.net/test_sep?retryWrites=true&w=majority
      - MONGO_URL_ADMIN=mongodb+srv://SEPU01:User123@sepcluster.yjn4m.mongodb.net/test_sep?retryWrites=true&w=majority
    ports:
      - "80:80"